/* Common non-tech job titles for the onboarding autocomplete.
   The AI adapts to anything typed; this just speeds the common cases. */
export const ROLES: string[] = [
  "Office Manager", "Administrative Assistant", "Executive Assistant", "Registered Nurse",
  "Licensed Practical Nurse", "Nursing Supervisor", "Medical Assistant", "Dental Hygienist",
  "Dental Assistant", "Sales Associate", "Sales Representative", "Account Manager",
  "Account Executive", "Regional Sales Manager", "Inside Sales Representative",
  "Project Coordinator", "Project Manager", "Program Manager", "Operations Manager",
  "Operations Coordinator", "Operations Analyst", "Customer Service Representative",
  "Customer Success Manager", "Call Center Representative", "Human Resources Coordinator",
  "Human Resources Manager", "HR Generalist", "Recruiter", "Talent Acquisition Specialist",
  "Benefits Administrator", "Marketing Coordinator", "Marketing Manager", "Brand Manager",
  "Social Media Manager", "Content Coordinator", "Communications Specialist", "Paralegal",
  "Legal Assistant", "Legal Secretary", "Social Worker", "Case Manager",
  "Community Outreach Coordinator", "Teacher", "Substitute Teacher", "Teaching Assistant",
  "Instructional Designer", "Corporate Trainer", "Training Coordinator", "Retail Manager",
  "Store Manager", "Assistant Store Manager", "Warehouse Supervisor", "Warehouse Associate",
  "Logistics Coordinator", "Supply Chain Analyst", "Procurement Specialist",
  "Inventory Manager", "Accounts Payable Clerk", "Accounts Receivable Specialist",
  "Bookkeeper", "Staff Accountant", "Accounting Manager", "Payroll Specialist",
  "Financial Analyst", "Budget Analyst", "Loan Officer", "Bank Teller", "Branch Manager",
  "Personal Banker", "Property Manager", "Leasing Consultant", "Real Estate Agent",
  "Front Desk Receptionist", "Receptionist", "Concierge", "Hotel Manager",
  "Hospitality Coordinator", "Event Coordinator", "Event Planner", "Catering Manager",
  "Restaurant Manager", "Pharmacy Technician", "Phlebotomist", "Patient Care Coordinator",
  "Physical Therapy Assistant", "Occupational Therapist", "Speech Therapist",
  "Home Health Aide", "Caregiver", "Childcare Provider", "Quality Assurance Specialist",
  "Compliance Officer", "Auditor", "Insurance Agent", "Claims Adjuster", "Underwriter",
  "Executive Director", "Nonprofit Program Director", "Development Manager", "Grant Writer",
  "Fundraising Coordinator", "Volunteer Coordinator", "Facilities Manager",
  "Maintenance Supervisor", "Building Engineer", "Production Supervisor",
  "Manufacturing Manager", "Plant Manager", "Construction Project Manager", "Estimator",
  "Site Superintendent", "Buyer", "Merchandiser", "Visual Merchandiser", "Data Entry Clerk",
  "Office Administrator", "Scheduling Coordinator", "Dispatcher", "Fleet Manager",
  "Transportation Coordinator", "Customer Experience Manager", "Client Relations Manager",
  "Member Services Coordinator", "Business Analyst", "Operations Director", "General Manager",
  "Veterinary Technician", "Veterinary Assistant", "Animal Care Specialist", "Librarian",
  "Archivist", "Research Assistant", "Graphic Designer", "Marketing Assistant",
  "Public Relations Specialist", "Sales Operations Manager", "Territory Manager",
  "District Manager", "Accountant", "Accounts Receivable Clerk", "Senior Financial Analyst",
  "Internal Auditor", "Tax Preparer", "Tax Accountant", "Controller", "Finance Manager",
  "Credit Analyst", "Mortgage Broker", "Financial Advisor", "Investment Analyst", "Actuary",
  "Billing Specialist", "Charge Nurse", "Nurse Practitioner", "Certified Nursing Assistant",
  "Patient Care Technician", "Medical Receptionist", "Medical Billing Specialist",
  "Medical Coder", "Health Information Technician", "Pharmacist", "Radiologic Technologist",
  "Respiratory Therapist", "Physical Therapist", "Physical Therapist Assistant",
  "Speech-Language Pathologist", "Medical Laboratory Technician", "Surgical Technologist",
  "Paramedic", "EMT", "Clinical Coordinator", "Healthcare Administrator", "Practice Manager",
  "Dietitian", "Behavioral Health Technician", "Mental Health Counselor",
  "Elementary School Teacher", "High School Teacher", "Special Education Teacher",
  "Paraprofessional", "Tutor", "Curriculum Developer", "School Counselor", "Principal",
  "Assistant Principal", "Registrar", "Admissions Counselor", "Academic Advisor",
  "Preschool Teacher", "Childcare Worker", "Learning and Development Specialist",
  "Software Engineer", "Frontend Developer", "Backend Developer", "Full Stack Developer",
  "Mobile Developer", "QA Engineer", "DevOps Engineer", "Site Reliability Engineer",
  "Data Analyst", "Data Scientist", "Data Engineer", "Machine Learning Engineer",
  "Product Manager", "Scrum Master", "Systems Analyst", "IT Support Specialist",
  "Help Desk Technician", "Network Administrator", "Systems Administrator",
  "Database Administrator", "Security Analyst", "Cloud Engineer", "Solutions Architect",
  "UX Designer", "UI Designer", "Product Designer", "Technical Writer", "IT Manager",
  "Engineering Manager", "Front Desk Coordinator", "Office Coordinator",
  "Facilities Coordinator", "Purchasing Manager", "Supply Chain Manager", "Warehouse Manager",
  "Forklift Operator", "Shipping and Receiving Clerk", "Logistics Manager", "Truck Driver",
  "Delivery Driver", "Courier", "Route Driver", "Distribution Manager", "Sales Manager",
  "Business Development Representative", "Business Development Manager",
  "Outside Sales Representative", "Sales Development Representative", "Retail Sales Associate",
  "Cashier", "Category Manager", "Marketing Specialist", "Digital Marketing Manager",
  "Content Marketing Manager", "SEO Specialist", "Email Marketing Specialist",
  "Product Marketing Manager", "Marketing Analyst", "Copywriter", "Content Writer",
  "Communications Manager", "Public Relations Manager", "Event Manager", "Art Director",
  "Creative Director", "Photographer", "Videographer", "Video Editor", "Motion Designer",
  "Web Designer", "Illustrator", "Production Assistant", "Customer Support Specialist",
  "Call Center Agent", "Technical Support Specialist", "Client Services Coordinator",
  "Support Team Lead", "Collections Specialist", "HR Coordinator", "Compensation Analyst",
  "HR Business Partner", "Employee Relations Specialist", "Attorney", "Contract Manager",
  "Legal Counsel", "Court Clerk", "Title Examiner", "Electrician", "Plumber",
  "HVAC Technician", "Carpenter", "Welder", "Machinist", "Millwright",
  "Maintenance Technician", "Maintenance Manager", "Facilities Technician", "Auto Mechanic",
  "Diesel Mechanic", "Automotive Technician", "Construction Manager", "Construction Worker",
  "Site Supervisor", "General Contractor", "Project Superintendent", "Surveyor", "Landscaper",
  "Groundskeeper", "Painter", "Roofer", "Mason", "Heavy Equipment Operator",
  "Production Worker", "Assembler", "Machine Operator", "Manufacturing Engineer",
  "Quality Control Inspector", "Quality Assurance Manager", "Process Engineer",
  "Industrial Engineer", "Line Lead", "Fabricator", "Chef", "Sous Chef", "Line Cook",
  "Prep Cook", "Pastry Chef", "Kitchen Manager", "Server", "Bartender", "Host", "Barista",
  "Food Service Worker", "Front Desk Agent", "Housekeeping Manager", "Housekeeper",
  "Banquet Manager", "Guest Services Representative", "Assistant Manager", "Shift Supervisor",
  "Team Lead", "Department Manager", "Director of Operations", "Vice President of Operations",
  "Chief Operating Officer", "Program Director", "Development Coordinator",
  "Nonprofit Program Manager", "Fundraising Manager", "Membership Coordinator", "Realtor",
  "Real Estate Broker", "Appraiser", "Escrow Officer", "Facilities Director", "Security Guard",
  "Security Officer", "Loss Prevention Specialist", "Police Officer", "Firefighter",
  "Corrections Officer", "Dispatcher (911)", "Flight Attendant", "Airline Pilot",
  "Air Traffic Controller",
];
