/* Common non-tech job titles for the onboarding autocomplete.
   The AI adapts to anything typed; this just speeds the common cases. */
export const ROLES: string[] = [
  "Office Manager", "Administrative Assistant", "Executive Assistant",
  "Registered Nurse", "Licensed Practical Nurse", "Nursing Supervisor",
  "Medical Assistant", "Dental Hygienist", "Dental Assistant",
  "Sales Associate", "Sales Representative", "Account Manager",
  "Account Executive", "Regional Sales Manager", "Inside Sales Representative",
  "Project Coordinator", "Project Manager", "Program Manager",
  "Operations Manager", "Operations Coordinator", "Operations Analyst",
  "Customer Service Representative", "Customer Success Manager", "Call Center Representative",
  "Human Resources Coordinator", "Human Resources Manager", "HR Generalist",
  "Recruiter", "Talent Acquisition Specialist", "Benefits Administrator",
  "Marketing Coordinator", "Marketing Manager", "Brand Manager",
  "Social Media Manager", "Content Coordinator", "Communications Specialist",
  "Paralegal", "Legal Assistant", "Legal Secretary",
  "Social Worker", "Case Manager", "Community Outreach Coordinator",
  "Teacher", "Substitute Teacher", "Teaching Assistant",
  "Instructional Designer", "Corporate Trainer", "Training Coordinator",
  "Retail Manager", "Store Manager", "Assistant Store Manager",
  "Warehouse Supervisor", "Warehouse Associate", "Logistics Coordinator",
  "Supply Chain Analyst", "Procurement Specialist", "Inventory Manager",
  "Accounts Payable Clerk", "Accounts Receivable Specialist", "Bookkeeper",
  "Staff Accountant", "Accounting Manager", "Payroll Specialist",
  "Financial Analyst", "Budget Analyst", "Loan Officer",
  "Bank Teller", "Branch Manager", "Personal Banker",
  "Property Manager", "Leasing Consultant", "Real Estate Agent",
  "Front Desk Receptionist", "Receptionist", "Concierge",
  "Hotel Manager", "Hospitality Coordinator", "Event Coordinator",
  "Event Planner", "Catering Manager", "Restaurant Manager",
  "Pharmacy Technician", "Phlebotomist", "Patient Care Coordinator",
  "Physical Therapy Assistant", "Occupational Therapist", "Speech Therapist",
  "Home Health Aide", "Caregiver", "Childcare Provider",
  "Quality Assurance Specialist", "Compliance Officer", "Auditor",
  "Insurance Agent", "Claims Adjuster", "Underwriter",
  "Executive Director", "Nonprofit Program Director", "Development Manager",
  "Grant Writer", "Fundraising Coordinator", "Volunteer Coordinator",
  "Facilities Manager", "Maintenance Supervisor", "Building Engineer",
  "Production Supervisor", "Manufacturing Manager", "Plant Manager",
  "Construction Project Manager", "Estimator", "Site Superintendent",
  "Buyer", "Merchandiser", "Visual Merchandiser",
  "Data Entry Clerk", "Office Administrator", "Scheduling Coordinator",
  "Dispatcher", "Fleet Manager", "Transportation Coordinator",
  "Customer Experience Manager", "Client Relations Manager", "Member Services Coordinator",
  "Business Analyst", "Operations Director", "General Manager",
  "Veterinary Technician", "Veterinary Assistant", "Animal Care Specialist",
  "Librarian", "Archivist", "Research Assistant",
  "Graphic Designer", "Marketing Assistant", "Public Relations Specialist",
  "Sales Operations Manager", "Territory Manager", "District Manager",
];
